# Auto-generated by generate_stubs.py — do not edit by hand.

def expand_message_xmd_sha512(msg, dst, len_in_bytes):
    """`expand_message_xmd` of RFC 9380 with SHA-512: expand `msg` under the domain separation tag"""
    ...

def hash_to_group(msg, dst):
    """`hash_to_ristretto255` (RFC 9380) with SHA-512 under the complete domain separation tag"""
    ...

def hash_to_scalar(msg, dst):
    """`HashToScalar` of the ristretto255-SHA512 ciphersuite of RFC 9497 under the complete domain"""
    ...
