//! Test vectors for the ristretto255-SHA512 ciphersuite of draft-doesburg-cfrg-coprf.
//!
//! The vectors in `tests/vectors/coprf-ristretto255.txt` are generated by this file and asserted
//! against it, so any change in derived factors, encodings, transcryption or proofs fails the
//! test. They are intended for the draft's "Test Vectors" appendix and for third-party
//! implementations checking interoperability.
//!
//! Every random input is fixed: the transcryptor secrets and identifiers are literals, and every
//! scalar the protocol samples (the blinding `b` of each encryption, the rerandomization `r` of
//! each transcryption, the batch permutation, and each proof's nonce) comes from a ChaCha20 RNG
//! with an explicit seed recorded in the file.
//!
//! To regenerate the file after an intended change:
//!
//! ```text
//! LIBPEP_WRITE_VECTORS=1 cargo test --test vectors
//! ```
//!
//! The vectors cover the batch operations and the verifiable session key share, so the test is
//! compiled out without those features. It is also compiled out under `elgamal3`, whose
//! ciphertext carries a third element: the draft's Ciphertext is `B || C`, 2 * Ne bytes, so the
//! `elgamal3` encoding is a different wire format and has no vectors in the draft. Every scalar
//! and Element below is identical under both encodings; only the ciphertexts differ.
//!
//! The vectors also assume the draft's `DeriveFactor`, so the test is compiled out under the
//! `legacy` and `hmac-derivation` features, which select other factor derivations.

#![cfg(all(
    feature = "batch",
    feature = "verifiable",
    not(feature = "legacy"),
    not(feature = "hmac-derivation"),
    not(feature = "elgamal3")
))]
#![allow(clippy::expect_used, clippy::unwrap_used)]

use libpep::contexts::{EncryptionContext, PseudonymizationDomain};
use libpep::data::simple::{ElGamalEncrypted, EncryptedAttribute, EncryptedPseudonym};
use libpep::elgamal::arithmetic::group_elements::{GroupElement, G};
use libpep::elgamal::arithmetic::scalars::{ScalarNonZero, ScalarTraits};
use libpep::elgamal::ElGamal;
use libpep::encodings::hash_to_group;
use libpep::factors::derivation::{LABEL_REKEY_ATTRIBUTE, LABEL_REKEY_PSEUDONYM, LABEL_RESHUFFLE};
use libpep::factors::{
    make_attribute_rekey_factor, make_pseudonym_rekey_factor, make_pseudonymisation_factor,
};
use libpep::factors::{
    AttributeRekeyInfo, EncryptionSecret, PseudonymizationInfo, PseudonymizationSecret, RekeyFactor,
};
use libpep::keys::distribution::proofs::{BlindingCommitment, SessionKeyShareProof};
use libpep::keys::traits::{PublicKey, SecretKey};
use libpep::keys::{
    make_attribute_session_keys, make_pseudonym_session_keys, AttributeGlobalSecretKey,
    PseudonymGlobalSecretKey,
};
use libpep::protocol::{Context, Mode};
use libpep::transcryptor::{pseudonymize_batch, rekey_batch};
use rand::rngs::ChaCha20Rng;
use rand::SeedableRng;
use std::fmt::Write as _;
use std::path::PathBuf;

/// The seed of every ChaCha20 RNG used below, recorded in the vectors file.
const SEED: [u8; 32] = *b"draft-doesburg-cfrg-coprf-00-vec";

/// A ChaCha20 RNG seeded with [`SEED`] and a one-byte stream label, so that each vector group
/// draws from its own reproducible stream.
fn rng_for(label: u8) -> ChaCha20Rng {
    let mut seed = SEED;
    seed[31] = label;
    ChaCha20Rng::from_seed(seed)
}

fn ciphertext_hex(c: &ElGamal) -> String {
    hex::encode(c.to_bytes())
}

/// Emit `Name = value` as the draft's appendix format uses it.
fn put(out: &mut String, name: &str, value: &str) {
    writeln!(out, "{name} = {value}").expect("writing to a String cannot fail");
}

/// The three `DeriveFactor` labels, each with its own secret and identifier.
fn vectors_derive_factor(out: &mut String, context: &Context) {
    let pseudo_secret =
        PseudonymizationSecret::from(b"transcryptor-1-pseudonymization-secret".to_vec());
    let enc_secret = EncryptionSecret::from(b"transcryptor-1-encryption-secret".to_vec());
    let domain = PseudonymizationDomain::from("domain-a");
    let session = EncryptionContext::from("session-a");

    out.push_str("// DeriveFactor, the three labels of Table 1.\n");
    out.push_str("// The secrets are ASCII byte strings, shown here as hex.\n\n");

    put(
        out,
        "PS_1",
        &hex::encode(b"transcryptor-1-pseudonymization-secret"),
    );
    put(
        out,
        "ES_1",
        &hex::encode(b"transcryptor-1-encryption-secret"),
    );
    put(out, "DomainIdentifier", &hex::encode(b"domain-a"));
    put(out, "SessionIdentifier", &hex::encode(b"session-a"));
    out.push('\n');

    let k = make_pseudonym_rekey_factor(&enc_secret, &session, context);
    put(
        out,
        "labelRekeyPseudonym",
        &format!("{LABEL_REKEY_PSEUDONYM:02x}"),
    );
    put(out, "k_c", &k.scalar().to_hex());
    put(out, "K_c", &(k.scalar() * G).to_hex());
    out.push('\n');

    let ka = make_attribute_rekey_factor(&enc_secret, &session, context);
    put(
        out,
        "labelRekeyAttribute",
        &format!("{LABEL_REKEY_ATTRIBUTE:02x}"),
    );
    put(out, "k'_c", &ka.scalar().to_hex());
    put(out, "K'_c", &(ka.scalar() * G).to_hex());
    out.push('\n');

    let s = make_pseudonymisation_factor(&pseudo_secret, &domain, context);
    put(out, "labelReshuffle", &format!("{LABEL_RESHUFFLE:02x}"));
    put(out, "s_d", &s.scalar().to_hex());
    put(out, "S_d", &(s.scalar() * G).to_hex());
}

/// EncryptPseudonym, TranscryptPseudonym and Decrypt with fixed `b` and `r`.
fn vectors_single_pseudonym(out: &mut String, context: &Context) {
    let mut rng = rng_for(0x01);

    let pseudo_secret =
        PseudonymizationSecret::from(b"transcryptor-1-pseudonymization-secret".to_vec());
    let enc_secret = EncryptionSecret::from(b"transcryptor-1-encryption-secret".to_vec());

    let domain_from = PseudonymizationDomain::from("domain-a");
    let domain_to = PseudonymizationDomain::from("domain-b");
    let session_from = EncryptionContext::from("session-a");
    let session_to = EncryptionContext::from("session-b");

    // The global key pair of the setup authority, fixed here rather than sampled.
    let y = ScalarNonZero::random(&mut rng);
    let global_secret = PseudonymGlobalSecretKey::from_scalar(y);

    let (pk_from, _sk_from) =
        make_pseudonym_session_keys(&global_secret, &session_from, &enc_secret, context);
    let (_pk_to, sk_to) =
        make_pseudonym_session_keys(&global_secret, &session_to, &enc_secret, context);

    // The identifier is encoded with hash_to_group, the encoding of the draft's enc-hash.
    let identifier = b"patient-42";
    let m = hash_to_group(identifier, context);

    // Enc(M, pk_from) with an explicit blinding scalar b.
    let b = ScalarNonZero::random(&mut rng);
    let ciphertext = ElGamal {
        gb: b * G,
        gc: m + b * *pk_from.value(),
    };
    let encrypted = EncryptedPseudonym::from_value(ciphertext);

    out.push_str("// EncryptPseudonym / TranscryptPseudonym / Decrypt, one ciphertext.\n");
    out.push_str("// y is the global secret key; b is the encryption blinding scalar;\n");
    out.push_str("// r is the rerandomization scalar of the transcryption.\n\n");

    put(out, "Identifier", &hex::encode(identifier));
    put(out, "M", &m.to_hex());
    put(out, "y", &y.to_hex());
    put(out, "Y", &(y * G).to_hex());
    put(out, "DomainFrom", &hex::encode(b"domain-a"));
    put(out, "DomainTo", &hex::encode(b"domain-b"));
    put(out, "SessionFrom", &hex::encode(b"session-a"));
    put(out, "SessionTo", &hex::encode(b"session-b"));
    put(out, "pk_from", &pk_from.value().to_hex());
    put(out, "b", &b.to_hex());
    put(out, "V", &ciphertext_hex(encrypted.value()));
    out.push('\n');

    // The transcryption factors, and the ratio actually applied.
    let info = PseudonymizationInfo::new(
        &domain_from,
        &domain_to,
        &session_from,
        &session_to,
        &pseudo_secret,
        &enc_secret,
        context,
    );
    put(out, "s", &info.s.scalar().to_hex());
    put(out, "k", &info.k.scalar().to_hex());

    // RRSK with an explicit r, matching the draft's TranscryptPseudonym.
    let r = ScalarNonZero::random(&mut rng);
    let s = info.s.scalar();
    let k = info.k.scalar();
    let rerandomized = ElGamal {
        gb: ciphertext.gb + r * G,
        gc: ciphertext.gc + r * *pk_from.value(),
    };
    let transcrypted = ElGamal {
        gb: s * k.invert() * rerandomized.gb,
        gc: s * rerandomized.gc,
    };
    put(out, "r", &r.to_hex());
    put(out, "V'", &ciphertext_hex(&transcrypted));
    put(out, "Y_to", &(k * *pk_from.value()).to_hex());
    out.push('\n');

    // Decrypt, and the same pseudonym reached by the library's own transcryption path.
    let decrypted = transcrypted.gc - sk_to.value() * transcrypted.gb;
    put(out, "P", &decrypted.to_hex());
    put(out, "sk_to", &sk_to.value().to_hex());

    // The pseudonym is s * M, independent of the rerandomization.
    assert_eq!(decrypted, s * m, "decryption must yield s * M");
}

/// A three-element batch in both modes, with the permutation drawn from the recorded seed.
fn vectors_batch(out: &mut String, context: &Context) {
    let mut rng = rng_for(0x02);

    let pseudo_secret =
        PseudonymizationSecret::from(b"transcryptor-1-pseudonymization-secret".to_vec());
    let enc_secret = EncryptionSecret::from(b"transcryptor-1-encryption-secret".to_vec());

    let domain_from = PseudonymizationDomain::from("domain-a");
    let domain_to = PseudonymizationDomain::from("domain-b");
    let session_from = EncryptionContext::from("session-a");
    let session_to = EncryptionContext::from("session-b");

    let y = ScalarNonZero::random(&mut rng);
    let pseudonym_global = PseudonymGlobalSecretKey::from_scalar(y);
    let y_attr = ScalarNonZero::random(&mut rng);
    let attribute_global = AttributeGlobalSecretKey::from_scalar(y_attr);

    let (pk_from, _) =
        make_pseudonym_session_keys(&pseudonym_global, &session_from, &enc_secret, context);
    let (_, sk_to) =
        make_pseudonym_session_keys(&pseudonym_global, &session_to, &enc_secret, context);
    let (apk_from, _) =
        make_attribute_session_keys(&attribute_global, &session_from, &enc_secret, context);
    let (_, ask_to) =
        make_attribute_session_keys(&attribute_global, &session_to, &enc_secret, context);

    out.push_str("// A batch of three pseudonyms (typePseudonym, 0x01) and three attributes\n");
    out.push_str("// (typeAttribute, 0x02). The permutation and every r are drawn from the\n");
    out.push_str("// recorded seed with stream label 02, so the output order is reproducible.\n\n");

    put(out, "BatchSeed", &hex::encode(rng_for(0x02).get_seed()));
    put(out, "typePseudonym", "01");
    put(out, "typeAttribute", "02");
    out.push('\n');

    // Three pseudonyms.
    let identifiers: [&[u8]; 3] = [b"patient-1", b"patient-2", b"patient-3"];
    let mut pseudonyms = Vec::new();
    for (i, id) in identifiers.iter().enumerate() {
        let m = hash_to_group(id, context);
        let b = ScalarNonZero::random(&mut rng);
        let c = ElGamal {
            gb: b * G,
            gc: m + b * *pk_from.value(),
        };
        put(out, &format!("PseudonymInput_{i}"), &hex::encode(id));
        put(out, &format!("PseudonymM_{i}"), &m.to_hex());
        put(out, &format!("PseudonymB_{i}"), &b.to_hex());
        put(out, &format!("PseudonymV_{i}"), &ciphertext_hex(&c));
        pseudonyms.push(EncryptedPseudonym::from_value(c));
    }
    out.push('\n');

    let info = PseudonymizationInfo::new(
        &domain_from,
        &domain_to,
        &session_from,
        &session_to,
        &pseudo_secret,
        &enc_secret,
        context,
    );

    let transcrypted = pseudonymize_batch(&mut pseudonyms.clone(), &info, &pk_from, &mut rng)
        .expect("batch pseudonymization should succeed");

    for (i, c) in transcrypted.iter().enumerate() {
        put(
            out,
            &format!("PseudonymOut_{i}"),
            &ciphertext_hex(c.value()),
        );
    }
    // The decrypted pseudonyms, and the permutation the shuffle applied. The pseudonym in
    // position j of the output is s * M of input PseudonymPermutation[j]; a verifier recomputes
    // s * M for each input and matches. The permutation is recorded so the vector is checkable,
    // but a transcryptor MUST NOT disclose it in a real deployment.
    let s = info.s.scalar();
    let mut permutation = Vec::new();
    for (i, c) in transcrypted.iter().enumerate() {
        let p = c.value().gc - sk_to.value() * c.value().gb;
        put(out, &format!("PseudonymP_{i}"), &p.to_hex());
        let source = (0..3)
            .find(|&j| s * hash_to_group(identifiers[j], context) == p)
            .expect("every output pseudonym comes from one of the inputs");
        permutation.push(source.to_string());
    }
    put(out, "PseudonymPermutation", &permutation.join(","));
    out.push('\n');

    // Three attributes, rekeyed only. Attributes are arbitrary group elements, so they are drawn
    // from the recorded stream rather than encoded from an identifier.
    let mut attributes = Vec::new();
    let mut attribute_messages = Vec::new();
    for i in 0..3u8 {
        let m = GroupElement::random(&mut rng);
        attribute_messages.push(m);
        let b = ScalarNonZero::random(&mut rng);
        let c = ElGamal {
            gb: b * G,
            gc: m + b * *apk_from.value(),
        };
        put(out, &format!("AttributeM_{i}"), &m.to_hex());
        put(out, &format!("AttributeB_{i}"), &b.to_hex());
        put(out, &format!("AttributeV_{i}"), &ciphertext_hex(&c));
        attributes.push(EncryptedAttribute::from_value(c));
    }
    out.push('\n');

    let rekey_info = AttributeRekeyInfo::new(&session_from, &session_to, &enc_secret, context);
    put(out, "k_attribute", &rekey_info.k.scalar().to_hex());

    let rekeyed = rekey_batch(&mut attributes.clone(), &rekey_info, &apk_from, &mut rng)
        .expect("batch rekeying should succeed");

    for (i, c) in rekeyed.iter().enumerate() {
        put(
            out,
            &format!("AttributeOut_{i}"),
            &ciphertext_hex(c.value()),
        );
    }
    // Rekeying leaves the message unchanged, so each output decrypts to one of the inputs and
    // the permutation can be read off directly.
    let mut permutation = Vec::new();
    for (i, c) in rekeyed.iter().enumerate() {
        let p = c.value().gc - ask_to.value() * c.value().gb;
        put(out, &format!("AttributeP_{i}"), &p.to_hex());
        let source = (0..3)
            .find(|&j| attribute_messages[j] == p)
            .expect("every output attribute comes from one of the inputs");
        permutation.push(source.to_string());
    }
    put(out, "AttributePermutation", &permutation.join(","));
}

/// A session key share with its proof, in modeVcoPRF.
fn vectors_session_key_share(out: &mut String) {
    let mut rng = rng_for(0x03);
    let context = Context::new(Mode::VcoPRF, libpep::protocol::RISTRETTO255_SHA512);

    let enc_secret = EncryptionSecret::from(b"transcryptor-1-encryption-secret".to_vec());
    let session = EncryptionContext::from("session-a");

    let k = make_pseudonym_rekey_factor(&enc_secret, &session, &context);
    let k_commitment = k.scalar() * G;

    let b = ScalarNonZero::random(&mut rng);
    let blinding_commitment = BlindingCommitment::new(&b);
    let u = b * k.scalar();

    let proof = SessionKeyShareProof::new(&b, &k_commitment, &mut rng);

    out.push_str("// A session key share with proof, modeVcoPRF (contextString mode byte 01).\n");
    out.push_str("// u_i is secret and is shown only so the vector can be reproduced.\n\n");

    put(out, "ContextString", &hex::encode(context.context_string()));
    put(out, "b_1", &b.to_hex());
    put(out, "B_1", &blinding_commitment.value().to_hex());
    put(out, "K_c_1", &k_commitment.to_hex());
    put(out, "u_1", &u.to_hex());
    put(out, "U_1", &proof.share_commitment().to_hex());

    assert!(
        proof.verify(&blinding_commitment, &k_commitment),
        "the session key share proof must verify"
    );
    assert_eq!(proof.share_commitment(), &(u * G), "U_1 must equal u_1 * G");
}

/// Build the whole vectors file.
fn generate() -> String {
    let context = Context::default();

    let mut out = String::new();
    out.push_str("# Test vectors for draft-doesburg-cfrg-coprf-00, ristretto255-SHA512.\n");
    out.push_str("#\n");
    out.push_str("# Generated by tests/vectors.rs in libpep; regenerate with\n");
    out.push_str("#   LIBPEP_WRITE_VECTORS=1 cargo test --test vectors\n");
    out.push_str("# and check the diff before committing.\n");
    out.push_str("#\n");
    out.push_str("# All values are hex. Scalars and Elements are 32 bytes (Ns = Ne = 32);\n");
    out.push_str("# a Ciphertext is B || C, 64 bytes. Byte strings (secrets, identifiers) are\n");
    out.push_str("# shown as the hex of their ASCII bytes.\n");
    out.push_str("#\n");
    out.push_str("# Every scalar the protocol samples is drawn from a ChaCha20 RNG seeded with\n");
    out.push_str("# Seed, with the last byte replaced by the stream label of each group, so a\n");
    out.push_str("# third-party implementation can reproduce the values exactly.\n\n");

    put(&mut out, "Ciphersuite", "ristretto255-SHA512");
    put(&mut out, "Mode", "modeCoPRF (0x00) unless stated otherwise");
    put(
        &mut out,
        "ContextString",
        &hex::encode(context.context_string()),
    );
    put(&mut out, "Seed", &hex::encode(SEED));
    out.push('\n');

    out.push_str("## DeriveFactor\n\n");
    vectors_derive_factor(&mut out, &context);
    out.push_str("\n## Single pseudonym\n\n");
    vectors_single_pseudonym(&mut out, &context);
    out.push_str("\n## Batch of three\n\n");
    vectors_batch(&mut out, &context);
    out.push_str("\n## Session key share (modeVcoPRF)\n\n");
    vectors_session_key_share(&mut out);

    out
}

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/vectors/coprf-ristretto255.txt")
}

/// Regenerate the vectors and compare them with the checked-in file.
///
/// Set `LIBPEP_WRITE_VECTORS=1` to rewrite the file instead of asserting.
#[test]
fn test_vectors_match_the_checked_in_file() {
    let generated = generate();
    let path = vectors_path();

    if std::env::var_os("LIBPEP_WRITE_VECTORS").is_some() {
        std::fs::create_dir_all(path.parent().expect("the vectors path has a parent"))
            .expect("creating the vectors directory should succeed");
        std::fs::write(&path, &generated).expect("writing the vectors file should succeed");
        return;
    }

    let checked_in = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "could not read {}: {e}. Regenerate with LIBPEP_WRITE_VECTORS=1 cargo test --test vectors",
            path.display()
        )
    });

    assert_eq!(
        generated,
        checked_in,
        "the generated test vectors differ from {}. If this change is intended, regenerate with \
         LIBPEP_WRITE_VECTORS=1 cargo test --test vectors",
        path.display()
    );
}
