# Auto-generated by scripts/generate_python_stubs.py — do not edit by hand.

def rekey(v, k):
    """Make a message encrypted under one key decryptable under another key."""
    ...

def rekey2(v, k_from, k_to):
    """A transitive and reversible n-PEP extension of [`rekey`], rekeying from one key to"""
    ...

def rerandomize(v, public_key, r):
    """Change the representation of a ciphertext without changing the contents."""
    ...

def reshuffle(v, s):
    """Change the contents of a ciphertext with factor `s`, i.e. message `M` becomes `s * M`."""
    ...

def reshuffle2(v, n_from, n_to):
    """A transitive and reversible n-PEP extension of [`reshuffle`], reshuffling from one pseudonym to"""
    ...

def rrsk(v, public_key, r, s, k):
    """Combination of [`rerandomize`], [`reshuffle`] and [`rekey`] (more efficient and secure than"""
    ...

def rrsk2(v, public_key, r, s_from, s_to, k_from, k_to):
    """A transitive and reversible n-PEP extension of [`rrsk`]."""
    ...

def rsk(v, s, k):
    """Combination of  [`reshuffle`] and [`rekey`] (more efficient and secure than applying them"""
    ...

def rsk2(v, s_from, s_to, k_from, k_to):
    """A transitive and reversible n-PEP extension of [`rsk`]."""
    ...
