# Auto-generated by generate_stubs.py — do not edit by hand.

class BatchError(PEPError):
    """A batch operation failed."""
    ...

class CacheFullError(CacheRegistrationError):
    """The commitment cache has reached its configured maximum size."""
    ...

class CacheRegistrationError(PEPError):
    """A commitment cache registration failed."""
    ...

class ConflictingValueError(CacheRegistrationError):
    """A different commitment is already registered under this key."""
    ...

class InconsistentStructureError(BatchError):
    """Items in the batch have inconsistent structures."""
    ...

class JsonFormatError(BatchError):
    """JSON value is malformed or has an unexpected structure."""
    ...

class JsonUnifyError(BatchError):
    """Failed to unify JSON structures across the batch."""
    ...

class MasterKeysNotRegisteredError(VerifyError):
    """Master keys are not registered for this transcryptor."""
    ...

class PEPError(Exception):
    """Base class for all libpep errors."""
    ...

class ProofRejectedError(VerifyError):
    """A zero-knowledge proof did not verify against the supplied statement."""
    ...

class SessionKeyShareError(PEPError):
    """Refused to generate a session-key share (e.g. weak blinding factor)."""
    ...

class UnknownCommitmentError(VerifyError):
    """No commitments registered for the requested transcryptor/transition."""
    ...

class VerifyError(PEPError):
    """A verifier check failed."""
    ...

class WeakBlindingError(SessionKeyShareError):
    """The supplied blinding factor was 1, which would leak the share scalar."""
    ...

class WeakCommitmentError(VerifyError):
    """A commitment is weak (equal to the identity or generator G) and was rejected."""
    ...
