# Auto-generated by generate_stubs.py — do not edit by hand.

def decode_lizard(element):
    """Invert `encode_lizard`; `None` if the element is not a lizard encoding (such as a"""
    ...

def encode_lizard(data):
    """The lizard encoding of a 16-byte string as a group element. Invertible with `decode_lizard`."""
    ...

def hash_to_group(x, context=None):
    """The hash_to_group encoding of an identifier: hash_to_ristretto255 (RFC 9380) domain-separated"""
    ...
