#!/usr/bin/env python3
"""Generate PEP 561 type stubs for the libpep Python module by introspection.

Run against a built module (``maturin develop`` first). Emits a ``libpep-stubs``
stub package into ``bindings/python/libpep-stubs``, which maturin includes in
the wheel. Parameter names come from the PyO3-generated text signatures;
parameter and return annotations are left open since the native module does not
carry them.

Usage: python scripts/generate_python_stubs.py [--check]

With ``--check``, exits non-zero if the stubs on disk differ from what would be
generated (used in CI to keep stubs in sync with the API).
"""

import inspect
import shutil
import sys
import tempfile
from pathlib import Path

import libpep
import libpep.client
import libpep.contexts
import libpep.data
import libpep.data.json
import libpep.elgamal
import libpep.elgamal.arithmetic
import libpep.elgamal.arithmetic.group_elements
import libpep.elgamal.arithmetic.scalars
import libpep.elgamal.primitives
import libpep.factors
import libpep.keys
import libpep.transcryptor

MODULES = {
    "__init__": libpep,
    "client": libpep.client,
    "contexts": libpep.contexts,
    "data/__init__": libpep.data,
    "data/json": libpep.data.json,
    "elgamal/__init__": libpep.elgamal,
    "elgamal/arithmetic/__init__": libpep.elgamal.arithmetic,
    "elgamal/arithmetic/group_elements": libpep.elgamal.arithmetic.group_elements,
    "elgamal/arithmetic/scalars": libpep.elgamal.arithmetic.scalars,
    "elgamal/primitives": libpep.elgamal.primitives,
    "factors": libpep.factors,
    "keys": libpep.keys,
    "transcryptor": libpep.transcryptor,
}

OUT = Path(__file__).resolve().parent.parent / "bindings" / "python" / "libpep-stubs"


def signature_of(obj, is_method: bool) -> str:
    text = getattr(obj, "__text_signature__", None)
    if text:
        params = text.strip("()")
        parts = [p.strip() for p in params.split(",") if p.strip() and p.strip() != "/"]
        parts = ["self" if p == "$self" else p for p in parts]
    else:
        parts = ["*args", "**kwargs"]
    if is_method and (not parts or parts[0] != "self"):
        parts = ["self"] + parts
    return "(" + ", ".join(parts) + ")"


def first_doc_line(obj) -> str | None:
    doc = inspect.getdoc(obj)
    if not doc:
        return None
    return doc.split("\n")[0].strip()


def stub_class(name: str, cls: type) -> list[str]:
    lines = [f"class {name}:"]
    doc = first_doc_line(cls)
    if doc:
        lines.append(f'    """{doc}"""')
    members = []
    for mname in sorted(dir(cls)):
        if mname.startswith("_") and mname not in ("__init__", "__eq__", "__len__"):
            continue
        member = inspect.getattr_static(cls, mname)
        obj = getattr(cls, mname)
        if isinstance(member, staticmethod) or (
            callable(obj) and getattr(obj, "__self__", None) is cls
        ):
            members.append(f"    @staticmethod")
            members.append(f"    def {mname}{signature_of(obj, False)}: ...")
        elif isinstance(member, property) or type(member).__name__ == "getset_descriptor":
            members.append(f"    @property")
            members.append(f"    def {mname}(self): ...")
        elif callable(obj):
            if mname == "__init__":
                ctor = getattr(cls, "__text_signature__", None)
                if ctor:
                    params = [p.strip() for p in ctor.strip("()").split(",") if p.strip()]
                    members.append(
                        "    def __init__(" + ", ".join(["self"] + params) + "): ..."
                    )
                else:
                    members.append("    def __init__(self, *args, **kwargs): ...")
            else:
                members.append(f"    def {mname}{signature_of(obj, True)}: ...")
    if not members:
        members = ["    ..."]
    return lines + members


def stub_module(mod) -> str:
    out = ["# Auto-generated by scripts/generate_python_stubs.py — do not edit by hand.", ""]
    names = [n for n in dir(mod) if not n.startswith("_")]
    submodule_names = set()
    for other in MODULES.values():
        if other is not mod and other.__name__.startswith(mod.__name__ + "."):
            submodule_names.add(other.__name__[len(mod.__name__) + 1 :].split(".")[0])
    for n in sorted(submodule_names & set(names)):
        out.append(f"from . import {n} as {n}")
    if submodule_names & set(names):
        out.append("")
    for n in sorted(names):
        if n in submodule_names:
            continue
        obj = getattr(mod, n)
        if inspect.ismodule(obj):
            continue
        if isinstance(obj, type):
            out.extend(stub_class(n, obj))
            out.append("")
        elif callable(obj):
            doc = first_doc_line(obj)
            out.append(f"def {n}{signature_of(obj, False)}:")
            if doc:
                out.append(f'    """{doc}"""')
            out.append("    ...")
            out.append("")
        else:
            out.append(f"{n}: object")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def generate(target: Path) -> None:
    if target.exists():
        shutil.rmtree(target)
    for rel, mod in MODULES.items():
        p = target / (rel + ".pyi")
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(stub_module(mod))


def main() -> int:
    if "--check" in sys.argv:
        with tempfile.TemporaryDirectory() as td:
            fresh = Path(td) / "libpep-stubs"
            generate(fresh)
            current = {p.relative_to(OUT): p.read_text() for p in OUT.rglob("*.pyi")}
            new = {p.relative_to(fresh): p.read_text() for p in fresh.rglob("*.pyi")}
            if current != new:
                changed = sorted(
                    set(current) ^ set(new)
                    | {k for k in set(current) & set(new) if current[k] != new[k]}
                )
                print("stubs out of date:", ", ".join(str(c) for c in changed))
                print("run: python scripts/generate_python_stubs.py")
                return 1
            print("stubs up to date")
            return 0
    generate(OUT)
    print(f"stubs written to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
